/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;

/**
 *
 * @author Ana Luiza
 */
public class FormRelatBalanco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelatBalanco.class.getName());

    public FormRelatBalanco() {
        initComponents();
        carregarProdutos();
    }

    private void carregarProdutos() {
        try {

            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{"Produto", "Qtd Estoque", "Valor Unit.", "Valor Total"}
            ) {
                public boolean isCellEditable(int row, int column) {
                    return column == 1 || column == 2;
                }
            };

            double totalEstoque = 0.0;

            String[] produtos = {"Arroz", "Feijão", "Macarrão", "Óleo"};
            java.util.Arrays.sort(produtos);
            java.util.Map<String, Integer> mapaQtds = new java.util.HashMap<>();
            mapaQtds.put("Arroz", 10);
            mapaQtds.put("Feijão", 5);
            mapaQtds.put("Macarrão", 20);
            mapaQtds.put("Óleo", 8);

            java.util.Map<String, Double> mapaValores = new java.util.HashMap<>();
            mapaValores.put("Arroz", 5.50);
            mapaValores.put("Feijão", 7.30);
            mapaValores.put("Macarrão", 3.40);
            mapaValores.put("Óleo", 6.80);

            for (String produto : produtos) {
                int qtd = mapaQtds.get(produto);
                double valorUnit = mapaValores.get(produto);
                double valorTotal = qtd * valorUnit;
                totalEstoque += valorTotal;

                modelo.addRow(new Object[]{
                    produto,
                    qtd,
                    valorUnit,
                    valorTotal
                });
            }

            tblProdutos.setModel(modelo);
            
            modelo.addTableModelListener(e -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                int row = e.getFirstRow();
                int column = e.getColumn();

                if (column == 1 || column == 2) { 
                    try {
                        int qtd = Integer.parseInt(modelo.getValueAt(row, 1).toString());
                        double valorUnit = Double.parseDouble(modelo.getValueAt(row, 2).toString());
                        double valorTotal = qtd * valorUnit;
                        modelo.setValueAt(valorTotal, row, 3);

                               
                         atualizarTotalEstoque();

                            } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Valores inválidos. Insira números válidos.");
                    }
                }
            }
        });
        lblTotalEstoque.setText("Valor Total do Estoque: R$ " + String.format("%.2f", totalEstoque));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage());
        }
    }

    private void atualizarTotalEstoque() {
        double totalEstoque = 0.0;
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            double valorTotal = Double.parseDouble(modelo.getValueAt(i, 3).toString());
            totalEstoque += valorTotal;
        }

        lblTotalEstoque.setText("Valor Total do Estoque: R$ " + String.format("%.2f", totalEstoque));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblTotalEstoque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade Estoque", "Valor Unitario", "Valor Total"
            }
        ));
        tblProdutos.setToolTipText("");
        jScrollPane1.setViewportView(tblProdutos);

        lblTotalEstoque.setText("Valor Total do Estoque: R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(lblTotalEstoque)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTotalEstoque)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new FormRelatBalanco().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalEstoque;
    private javax.swing.JTable tblProdutos;
    // End of variables declaration//GEN-END:variables
}
