/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Ana Luiza & Beatriz Arevalo
 */
public class FormMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName());

    /**
     * Creates new form FormMenuPrincipal
     */
    public FormMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadastroCategoria = new javax.swing.JMenuItem();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jMenuItemCadastroUnMedida = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenItemEntradas = new javax.swing.JMenuItem();
        jMenuIntemSaidas = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemRelatListaPreco = new javax.swing.JMenuItem();
        jRelatBalanco = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Estoque");

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadastroCategoria.setText("Cadastrar categoria");
        jMenuItemCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastroCategoria);

        jMenuItemCadastroProduto.setText("Cadastrar produtos");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastroProduto);

        jMenuItemCadastroUnMedida.setText("Cadastrar unidade de medida");
        jMenuItemCadastroUnMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUnMedidaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastroUnMedida);

        jMenuBar1.add(jMenuCadastros);

        jMenu1.setText("Movimentação");

        jMenItemEntradas.setText("Entradas");
        jMenItemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenItemEntradasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenItemEntradas);

        jMenuIntemSaidas.setText("Saídas");
        jMenuIntemSaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIntemSaidasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIntemSaidas);

        jMenuBar1.add(jMenu1);

        jMenuRelatorio.setText("Relatórios");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });

        jMenuItemRelatListaPreco.setText("Lista de Preços");
        jMenuItemRelatListaPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatListaPrecoActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemRelatListaPreco);

        jRelatBalanco.setText("Balanço Físico e Financeiro");
        jRelatBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatBalancoActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jRelatBalanco);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroCategoriaActionPerformed
        FormCadastroCat objeto = new FormCadastroCat();
        objeto.setVisible(true);

    }//GEN-LAST:event_jMenuItemCadastroCategoriaActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        FormCadastroProd objeto = new FormCadastroProd();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jMenuItemCadastroUnMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUnMedidaActionPerformed
        FormCadastroUniMedida objeto = new FormCadastroUniMedida();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroUnMedidaActionPerformed

    private void jMenuItemRelatListaPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatListaPrecoActionPerformed
        RelatListaPreco objeto = new RelatListaPreco();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatListaPrecoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        // TODO add your handlig code here:
    }//GEN-LAST:event_jMenuRelatorioActionPerformed

    private void jRelatBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatBalancoActionPerformed
        FormRelatBalanco objeto = new FormRelatBalanco();
        objeto.setVisible(true);
    }//GEN-LAST:event_jRelatBalancoActionPerformed

    private void jMenuIntemSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIntemSaidasActionPerformed
     FormSaidaEstoque objeto = new FormSaidaEstoque();
objeto.setVisible(true);
    }//GEN-LAST:event_jMenuIntemSaidasActionPerformed

    private void jMenItemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenItemEntradasActionPerformed
             FormEntradaEstoque objeto = new FormEntradaEstoque();
objeto.setVisible(true);
    }//GEN-LAST:event_jMenItemEntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenItemEntradas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuIntemSaidas;
    private javax.swing.JMenuItem jMenuItemCadastroCategoria;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemCadastroUnMedida;
    private javax.swing.JMenuItem jMenuItemRelatListaPreco;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenuItem jRelatBalanco;
    // End of variables declaration//GEN-END:variables
}
