/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Ana Luiza
 */
public class FormCadastroUniMedida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadastroUniMedida.class.getName());

    /**
     * Creates new form FormCadastroUniMedida
     */
    public FormCadastroUniMedida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroUnidadeMedida = new javax.swing.JLabel();
        NomeUnidadeMedida = new javax.swing.JLabel();
        inputTextUnidadeMedida = new javax.swing.JTextField();
        btnCadastrarUnidadeMedida = new javax.swing.JButton();
        btnCancelarCadUnidadeMedida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Unidade de Medida");

        CadastroUnidadeMedida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CadastroUnidadeMedida.setText("Cadastro de Unidade de Medida");

        NomeUnidadeMedida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NomeUnidadeMedida.setText("Nome:");

        btnCadastrarUnidadeMedida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarUnidadeMedida.setText("Cadastrar");
        btnCadastrarUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUnidadeMedidaActionPerformed(evt);
            }
        });

        btnCancelarCadUnidadeMedida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarCadUnidadeMedida.setText("Cancelar");
        btnCancelarCadUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadUnidadeMedidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CadastroUnidadeMedida)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeUnidadeMedida)
                        .addGap(68, 68, 68)
                        .addComponent(inputTextUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarCadUnidadeMedida)
                        .addGap(49, 49, 49)
                        .addComponent(btnCadastrarUnidadeMedida)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CadastroUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeUnidadeMedida)
                    .addComponent(inputTextUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCadUnidadeMedida)
                    .addComponent(btnCadastrarUnidadeMedida))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUnidadeMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarUnidadeMedidaActionPerformed

    private void btnCancelarCadUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadUnidadeMedidaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarCadUnidadeMedidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadastroUniMedida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroUnidadeMedida;
    private javax.swing.JLabel NomeUnidadeMedida;
    private javax.swing.JButton btnCadastrarUnidadeMedida;
    private javax.swing.JButton btnCancelarCadUnidadeMedida;
    private javax.swing.JTextField inputTextUnidadeMedida;
    // End of variables declaration//GEN-END:variables
}
