/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.JOptionPane;
import modelo.Produto;

/**
 *
 * @author Ana Luiza & Beatriz Arevalo
 */
public class FormCadastroProd extends javax.swing.JFrame {

    private Produto objetoProduto;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadastroProd.class.getName());

    public FormCadastroProd() {
        initComponents();
        this.objetoProduto = new Produto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        CadProdutos = new javax.swing.JLabel();
        NomeProd = new javax.swing.JLabel();
        PrecoProd = new javax.swing.JLabel();
        QuantidadeProd = new javax.swing.JLabel();
        QuantidadeMinProd = new javax.swing.JLabel();
        inputTextPrecoProduto = new javax.swing.JTextField();
        inputTextQtdMinProduto = new javax.swing.JTextField();
        inputTextQuantProduto = new javax.swing.JTextField();
        QuantidadeMaxProd = new javax.swing.JLabel();
        inputTextQtdMaxProduto = new javax.swing.JTextField();
        inputTextNomeProduto = new javax.swing.JTextField();
        btnCancelarCadProd = new javax.swing.JButton();
        btnCadastroProd = new javax.swing.JButton();
        Categoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        unidadeDeMedida = new javax.swing.JLabel();
        inputTextUniMedida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Produtos");

        CadProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CadProdutos.setText("Cadastro de Produto");

        NomeProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NomeProd.setText("Nome:");

        PrecoProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PrecoProd.setText("Preço:");

        QuantidadeProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantidadeProd.setText("Quantidade:");

        QuantidadeMinProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantidadeMinProd.setText("Quantidade Mínima:");

        QuantidadeMaxProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantidadeMaxProd.setText("Quantidade Máxima:");

        btnCancelarCadProd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelarCadProd.setText("Cancelar");
        btnCancelarCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadProdActionPerformed(evt);
            }
        });

        btnCadastroProd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCadastroProd.setText("Cadastrar");
        btnCadastroProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProdActionPerformed(evt);
            }
        });

        Categoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Categoria.setText("Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        unidadeDeMedida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unidadeDeMedida.setText("Unidade de medida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CadProdutos)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnCancelarCadProd)
                .addGap(82, 82, 82)
                .addComponent(btnCadastroProd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unidadeDeMedida)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QuantidadeProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputTextQuantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QuantidadeMinProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputTextQtdMinProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputTextNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PrecoProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputTextPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuantidadeMaxProd)
                                    .addComponent(Categoria))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputTextQtdMaxProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputTextUniMedida, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CadProdutos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeProd)
                    .addComponent(inputTextNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecoProd)
                    .addComponent(inputTextPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantidadeProd)
                    .addComponent(inputTextQuantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantidadeMinProd)
                    .addComponent(inputTextQtdMinProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextQtdMaxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantidadeMaxProd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadeDeMedida)
                    .addComponent(inputTextUniMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCadProd)
                    .addComponent(btnCadastroProd))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadProdActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarCadProdActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void btnCadastroProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdActionPerformed
        try {
            // recebendo e validando dados da interface gráfica.
            String nome = "";
            double preco = 0;
            int quantidade = 0;
            String uni_medida = "";
            int qtd_minima = 0;
            int qtd_maxima = 0;
            int categoria_id = 0;
            String categoria = "";

            if (this.inputTextNomeProduto.getText().length() < 2) {
                throw new Mensagem("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.inputTextNomeProduto.getText();
            }

            if (this.inputTextPrecoProduto.getText().length() <= 0) {
                throw new Mensagem("Preço deve ser número e maior que zero.");
            } else {
                preco = Integer.parseInt(this.inputTextPrecoProduto.getText());
            }

            if (this.inputTextQtdMinProduto.getText().length() < 0) {
                throw new Mensagem("Quantidade minima deve ser número e maior que zero.");
            } else {
                qtd_minima = Integer.parseInt(this.inputTextQtdMinProduto.getText());
            }

            if (this.inputTextQtdMaxProduto.getText().length() < 0) {
                throw new Mensagem("Quantidade maxima deve ser número e maior que zero.");
            } else {
                qtd_maxima = Integer.parseInt(this.inputTextQtdMaxProduto.getText());
            }

            if (this.inputTextQuantProduto.getText().length() < 0) {
                throw new Mensagem("Quantidade deve ser número e maior que zero.");
            } else {
                quantidade = Integer.parseInt(this.inputTextQuantProduto.getText());
            }

            if (this.inputTextUniMedida.getText().length() < 2) {
                throw new Mensagem("Unidade de medida deve conter ao menos 1 caractere.");
            } else {
                uni_medida = this.inputTextUniMedida.getText();
            }

           
          
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número válido.");
        }
    }//GEN-LAST:event_btnCadastroProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadastroProd().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadProdutos;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel NomeProd;
    private javax.swing.JLabel PrecoProd;
    private javax.swing.JLabel QuantidadeMaxProd;
    private javax.swing.JLabel QuantidadeMinProd;
    private javax.swing.JLabel QuantidadeProd;
    private javax.swing.JButton btnCadastroProd;
    private javax.swing.JButton btnCancelarCadProd;
    private javax.swing.JTextField inputTextNomeProduto;
    private javax.swing.JTextField inputTextPrecoProduto;
    private javax.swing.JTextField inputTextQtdMaxProduto;
    private javax.swing.JTextField inputTextQtdMinProduto;
    private javax.swing.JTextField inputTextQuantProduto;
    private javax.swing.JTextField inputTextUniMedida;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel unidadeDeMedida;
    // End of variables declaration//GEN-END:variables
}
